# Generated by Django 5.1.7 on 2025-03-29 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_url_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_team', models.CharField(choices=[('ARI', 'Arizona Diamondbacks'), ('ATL', 'Atlanta Braves'), ('BAL', 'Baltimore Orioles'), ('BOS', 'Boston Red Sox'), ('CHC', 'Chicago Cubs'), ('CWS', 'Chicago White Sox'), ('CIN', 'Cincinnati Reds'), ('CLE', 'Cleveland Guardians'), ('COL', 'Colorado Rockies'), ('DET', 'Detroit Tigers'), ('HOU', 'Houston Astros'), ('KC', 'Kansas City Royals'), ('LAA', 'Los Angeles Angels'), ('LAD', 'Los Angeles Dodgers'), ('MIA', 'Miami Marlins'), ('MIL', 'Milwaukee Brewers'), ('MIN', 'Minnesota Twins'), ('NYM', 'New York Mets'), ('NYY', 'New York Yankees'), ('OAK', 'Oakland Athletics'), ('PHI', 'Philadelphia Phillies'), ('PIT', 'Pittsburgh Pirates'), ('SD', 'San Diego Padres'), ('SF', 'San Francisco Giants'), ('SEA', 'Seattle Mariners'), ('STL', 'St. Louis Cardinals'), ('TB', 'Tampa Bay Rays'), ('TEX', 'Texas Rangers'), ('TOR', 'Toronto Blue Jays'), ('WSH', 'Washington Nationals'), ('Other', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
