# Generated by Django 5.1.7 on 2025-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_sports_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
