# Generated by Django 5.1.7 on 2025-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_teams_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
