# Generated by Django 5.1.7 on 2025-04-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_leaderboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-upvotes']},
        ),
    ]
