# Generated by Django 5.1.7 on 2025-04-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_leaderboard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.team'),
        ),
    ]
