# Generated by Django 5.1.7 on 2025-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_userprofile_favorite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
