# Generated by Django 5.1.7 on 2025-04-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_team_stadium_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium_alt',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
